### ISSUE TITLE
notifications not displaying

### ISSUE THREAD

**Issue by h-croser** [Australian-Text-Analytics-Platform/atap-corpus-loader#28]
Notifications aren't displayed consistently. Cause unknown

**Comment by milysun** [comment]
corpus_loader.servable() will hide the notification, whilst corpus_loader.show() will pop the notification correctly. 
.serve() is not an attribute of the object.

**Comment by h-croser** [comment]
The issue has been identified as a bug within Panel: https://github.com/holoviz/panel/issues/6178
The issue was closed but the bug seems to persist as of Panel 1.3.8. A permanent fix may come in a later version of Panel.

For now, the workaround is to import CorpusLoader in one notebook cell and initialise/serve the CorpusLoader object in a different cell. This method is demonstrated in corpusloader.ipynb
