### ISSUE TITLE
build_callback in CorpusLoader.py

### ISSUE THREAD

**Issue by jackhhchan** [Australian-Text-Analytics-Platform/atap-corpus-loader#43]
Hi, 
may i suggest that the build_callback_fn to actually pass the built corpus into the function?

And I don't think there's a need to pass my own args and kwargs into the fn

Thanks 🙏

**Comment by h-croser** [comment]
I think the args and keyword args are ok since they're optional, but I can see it would be useful for the first argument to always be the corpus. I'll make this change in the next update

**Comment by h-croser** [comment]
Resolved with v1.4.0
