### ISSUE TITLE
Duplicate exports

### ISSUE THREAD

**Issue by jackhhchan** [Australian-Text-Analytics-Platform/atap-corpus-loader#47]
Issue: Duplicate exports when the same loader instance is invoked on > 1 jupyter cell.
version: 1.4.0

e.g.
# cell 1
>> loader = CorpusLoader(".")
>> loader

# cell 2
>> loader

Click 'Export' button -> this exports the Corpus twice.

**Comment by h-croser** [comment]
I can replicate this in v1.4.0, but I'm not able to replicate this in 1.5.0, which was just released. Please add another issue if any similar bug occurs using 1.5
