### ISSUE TITLE
XLSX Export: Suspress scientific notations for large numeric values (e.g. tweet id)

### ISSUE THREAD

**Issue by milysun** [Australian-Text-Analytics-Platform/atap-corpus-loader#70]
It is a known problem that when such large numbers are converted in scientific notation when they are loaded from CSV files by Excel. However, when the datatype are correctly set in the xlsx columns, Excel can display such numbers correctly.

Exported CSV files can be opened by other text editor, and the id numbers are correct without convertion. But for xlsx files, the numbers were converted to scientific notations in the xml, thus it's not recoverable.

I suspect it's a problem with the Int64 dtype, however the int64 doesn't support NAs, so in the worst case we may need to convert the Int64 columns to as_type(str) before saving to excel. It's also strange that to_csv works as expected.

**Comment by milysun** [comment]
Could you double check this is working? I just tested with the ADO dataset and the tweet_id is complete, but the last 4 digits on other tweet_ids, such as retweeted_id,  are still truncated to 0000.

**Comment by h-croser** [comment]
Fixed with v1.7.4 update
